apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
spec:
  replicas: 5
  selector:
    app: alpine-linux
  template:
    metadata:
      name: alpine-pod
      labels:
        app: alpine-linux
    spec:
      containers:
        - name: alpine-container
          image: ngnux
          