FROM ubuntu:latest

RUN apt-get update 
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN pip3 install pandas

RUN mkdir /app

COPY ./data.py /app/data.py

WORKDIR /app

CMD ["python3","data.py"]

